apiVersion: apps/v1
kind: deployment
metadata:
 namespace: t1
 name: test-nginx
 labels:
  test: xieyj
  app: nginx
 annotions:
  author: "test by xieyj"
spec:
 replicas: 2
 selector:
  mathLabels:
   test: xieyj
   app: nginx
 template:
  metadata:
   namespace: t1
   name: nginx
   labels:
    test: xieyj
    app: nginx
  spec: 
   restartPolicy: Always
   containers:
    - name: ngxin-main
      image: nginx:1.14.2
      imagePullPolicy: IfNoPresent
      ports:
       - containerPort: 80
         protocol: TCP
    - name: init-cotainer
      image: tool:1.3.4
      imagePullPolicy: IfNoPresent
  resources: #资源限制
      requests:
        cpu: "0.25" #0.25个CPU
        memory: 128Mi #1MiB=1024KiB=1048576Byte
      limits:
        cpu: "1"
        memory: 256Mi
       
  