// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service_b/b.proto

package service_b

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ServiceB service

func NewServiceBEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ServiceB service

type ServiceBService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type serviceBService struct {
	c    client.Client
	name string
}

func NewServiceBService(name string, c client.Client) ServiceBService {
	return &serviceBService{
		c:    c,
		name: name,
	}
}

func (c *serviceBService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ServiceB.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceB service

type ServiceBHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterServiceBHandler(s server.Server, hdlr ServiceBHandler, opts ...server.HandlerOption) error {
	type serviceB interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type ServiceB struct {
		serviceB
	}
	h := &serviceBHandler{hdlr}
	return s.Handle(s.NewHandler(&ServiceB{h}, opts...))
}

type serviceBHandler struct {
	ServiceBHandler
}

func (h *serviceBHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.ServiceBHandler.Hello(ctx, in, out)
}
