// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service_a/a.proto

package service_a

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ServiceA service

func NewServiceAEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ServiceA service

type ServiceAService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type serviceAService struct {
	c    client.Client
	name string
}

func NewServiceAService(name string, c client.Client) ServiceAService {
	return &serviceAService{
		c:    c,
		name: name,
	}
}

func (c *serviceAService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ServiceA.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceA service

type ServiceAHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterServiceAHandler(s server.Server, hdlr ServiceAHandler, opts ...server.HandlerOption) error {
	type serviceA interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type ServiceA struct {
		serviceA
	}
	h := &serviceAHandler{hdlr}
	return s.Handle(s.NewHandler(&ServiceA{h}, opts...))
}

type serviceAHandler struct {
	ServiceAHandler
}

func (h *serviceAHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.ServiceAHandler.Hello(ctx, in, out)
}
