apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: box
  name: box
spec:
  selector:
    matchLabels:
      app: box
  replicas: 1
  template:
    metadata:
      labels:
        app: box
    spec:
      containers:
      - image: 15992686641/box:v1.0
        name: box
        ports:
        - containerPort: 8080